server:
  port: 8001
spring:
  application:
    name: hr-worker
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  main:
    allow-bean-definition-overriding: true  
eureka:
  client:
    service-url:  
      defaultZone: http://127.0.0.1:8761/eureka
      

  
  